name: Latest blog post workflow
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://shinhyeong.github.io/feed.xml"
          max_post_count: 5
          # 위젯 느낌을 내기 위해 표(Table) 행 형식으로 템플릿 지정
          template: "<tr><td width='20%'>DATE</td><td width='80%'><a href='$url'><b>$title</b></a><br/>$description</td></tr>"
          date_format: "yyyy.mm.dd"
