name: Latest blog post workflow
on:
  schedule: # 매시간마다 자동으로 실행 (원하는 시간으로 cron 변경 가능)
    - cron: '0 * * * *'
  workflow_dispatch: # 수동으로 실행 가능하도록 설정

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://shinhyeong.github.io/feed.xml"
          max_post_count: 5 # 보여줄 게시글 개수 (기본값: 5)
          template: "$newline - 📝 [$title]($url) ($date)"
          date_format: "yyyy.mm.dd"
